### ISSUE TITLE
Function MoteusAPI.ReadState returns position only in the interval +-3.2767

### ISSUE THREAD

**Issue by doloi456** [sinaaghli/moteus_cpp#2]
Hello,
I run the example "main_readstate.cpp" and it seems that the function **MoteusAPI.ReadState** returns the state correctly in the interval **+-3.2767**. Then, the displayed **position** stays at that (+/-) value.

Thanks!

**Comment by sinaaghli** [comment]
Hello @doloi456 ,
when you reset the states [here](https://github.com/sinaaghli/moteusapi/blob/0eca0ce27df4f918b210ecb2bc4f411b6cc68927/example_internal/main_readstate.cpp#L17) then the position as well as every other state gets disable and on the next line it only enables velocity and torque readings. 
if you want the position too you should not reset the state. let me know if that works!

**Comment by doloi456** [comment]
Hello @sinaaghli ,
sorry, I did not describe my problem exactly. The problem is only in **position** read-out. In the example **MoteusAPI.ReadState.cpp**, I commented out the line 17 (together with all lines below), and the issue still persists. For instance, I positioned the motor to a position outside the interval <-3.2767, 3.2767> (checked via TVIEW) and ran the example. The output value, however, still stayed at the value +-3.2767.

Thank you for your help (and also for the API),
Loi

**Comment by sinaaghli** [comment]
O that is probably some feature from firmware in moteus boards. Let me check with [@jpieper](https://github.com/jpieper) and see if thats a known feature. there might be a different variable to read the position regardless of limits. I'll get back to you!

**Comment by georgevargas** [comment]
Hi,
I see the exact same issue. I get correct position values as long as my actual position is between -3.2 and +3.2,otherwise it clamps to -3.2767 or +3.2747. 

I love this API, I created  a qtcreator gui that uses it and it works flawlessly other than the issue mentioned above.
It would be nice if I could get a code example which would  automatically read the dev_name from the system, instead of hard-coding it.
Thank you very much!

![image0](https://user-images.githubusercontent.com/10259360/182048111-b3febbde-b1e6-4897-92ac-c7e3c6ed144a.jpeg)

**Comment by jpieper** [comment]
That is because the API here does not allow you to select the resolution you want, and always uses int16, which is limited to +-3.2767

If you look, here https://github.com/sinaaghli/moteusapi/blob/0eca0ce27df4f918b210ecb2bc4f411b6cc68927/moteusapi/moteus_protocol.h#L692 the structure defaults to int16.  If you want something else, you need to provide `ReadState` or the class with a way to set them.

**Comment by georgevargas** [comment]
Thank you, That fixed it.
I edited moteus_protocol.h in moteusapi-main/moteusapi and changed the following lines in struct QueryCommand;
  Resolution mode = Resolution::kFloat;
  Resolution position = Resolution::kFloat;
  Resolution velocity = Resolution::kFloat;
  Resolution torque = Resolution::kFloat;
  Resolution q_current = Resolution::kFloat;     // was kIgnore
  Resolution d_current = Resolution::kFloat;     // was kIgnore
  Resolution rezero_state = Resolution::kInt16;  // was kIgnore
  Resolution voltage = Resolution::kFloat;
  Resolution temperature = Resolution::kFloat;
  Resolution fault = Resolution::kInt8;

Then followed the instructions to install in the system;
> cd moteusapi-main/build
> cmake ..
> sudo make install 

Now the position reads back correctly.
Thank you!
